### ISSUE TITLE
Possible to run it on raspberry pi?

### ISSUE THREAD

**Issue by xses22** [radinshayanfar/TGCopyBot#1]
Hey there I have the Bot running on a V Server but I would like to get this running local on a pi but I'm not able to get it running with docker. Is the pi not able tp run this container?

Thanks in advance.

> Successfully tagged copybot:latest
> WARNING: Image for service bot was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
> Creating tgcopybot_bot_run ... done
> Traceback (most recent call last):
>   File "app/main.py", line 19, in <module>
>     tg = Telegram(
>   File "/usr/local/lib/python3.8/dist-packages/telegram/client.py", line 113, in __init__
>     self._tdjson = TDJson(library_path=library_path, verbosity=tdlib_verbosity)
>   File "/usr/local/lib/python3.8/dist-packages/telegram/tdjson.py", line 27, in __init__
>     self._build_client(library_path, verbosity)
>   File "/usr/local/lib/python3.8/dist-packages/telegram/tdjson.py", line 36, in _build_client
>     self._tdjson = CDLL(library_path)
>   File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
>     self._handle = _dlopen(self._name, mode)
> OSError: /usr/local/lib/python3.8/dist-packages/telegram/lib/linux/libtdjson.so: wrong ELF class: ELFCLASS64
> ERROR: 1

**Comment by radinshayanfar** [comment]
Hi!
I'm not familiar with the Raspberry Pi. Can you test [this issue](https://github.com/alexander-akhmetov/python-telegram/issues/16) if it works or not? Building TDlib from the source isn't that much hard. Just follow [the instructions](https://github.com/tdlib/td#building) and make sure to install [dependencies](https://github.com/tdlib/td#dependencies) before that.

**Comment by xses22** [comment]
Just switched to Raspbian 64Bit os but stil the same error. Will try your post now.

**Comment by xses22** [comment]
Wasn't able to get it up and running but I think it has something to do with switching to 64bit Kernel on the pi.

Just a quick question, this bot does something like selecting text ctrl + c, and then ctrl + v on another chat? Would someone be able to spot if I copied the text in his channel, because if someone forwards text he could see it.

Thanks for your help.

**Comment by radinshayanfar** [comment]
I think so too that your problem is related to not using 64 bit OS. If you weren't able to fix it, it'd be better to open a new issue for [TDlib](https://github.com/tdlib/td)'s repository.

And about your question. Yes, it does. That's the main idea behind developing this bot, not to mention where the message was forwarded from.
